# in production this should probably be busybox, but let's use ubuntu for a
# fair comparison 
# FROM tutum/ubuntu-saucy
FROM tutum/ubuntu

MAINTAINER Ram Rajamony, rajamon@us.ibm.com

RUN apt-get -qq install -y libgomp1 numactl
RUN apt-get update
ADD bin /
CMD numactl --physcpubind=0-31 --interleave=0,1 /gups.exe
